### ISSUE TITLE
HRTF data link unvalid

### ISSUE THREAD

**Issue by xiaozhi2015** [TheKangChen/virtual-surround-sound#1]
HRTF data from CIPIC database by UC Davis: https://www.ece.ucdavis.edu/cipic/spatial-sound/hrtf-data/
@TheKangChen

**Comment by TheKangChen** [comment]
Thanks for letting me know the link is dead. It seems like UC Davis has taken down their CIPIC database website at the moment so there's currently no way to access their HRTF files.

Code here will still work with other databases, but you'll have to update the format and layout of each azimuth and elevation manually to fit the new database you want to use.
